name = "TradingPipeline"
uuid = "c16697eb-6b76-47e5-bb18-571408685438"
authors = ["contributors"]
version = "0.1.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DocStringExtensions = "0.9.3"
Printf = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
